version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    networks:
        - clickhouse
    ports:
      - "8123:8123"
    volumes:
      - ./ddl/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./dml/insertdb.sql:/docker-entrypoint-initdb.d/insertdb.sql
volumes:
  clickhouse-data:
networks:
    clickhouse: